server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: boot-study-server
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.109:3306/boot_study?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1q2w3e$R
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
#  sql:
#    init:
#      mode: always
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 120MB
  devtools:
    livereload:
      enabled: true